public enum TODOList {

	//DIALOGUE ITEM
	DIALOGUE_ITEM_INSPECTOR,


	//DIALOGUE EDITOR
	DIALOGUE_EDITOR_SAVE,
	DIALOGUE_EDITOR_LOAD,
	DIALOGUE_EDITOR_ZOOM,
	DIALOGUE_EDITOR_CONNECTING_LINES,

	//LOCALIZATION
	LOCALIZATION_LOC_FILES,
	LOCALIZATION_LOCALIZE
}